### PR TITLE
Fix: tests for 2.7 and 3.5

### PR DESCRIPTION
**Pull request by anki-code**
Related to #31 #32

### CODE REVIEW

**Comment by anki-code** [comment]
Hi @niess! Please take a look.

**Comment by niess** [comment]
Fine, I see. I am just wondering about the following. My understanding is that it fails in 2.7 and 3.5 because the pip version differs. Right?
But let's say that the pip versions gets updated for the 3.5 AppImage. Then the behaviour of app build would no more be correct isn't it?

If so, wouldn't it be better to check the pip version instead of the python one. E.g. by issuing a `system('AppRun -m pip --version ')` first and parsing out the result.

**Comment by anki-code** [comment]
@niess yep, take a look again ;)

**Comment by niess** [comment]
@anki-code Great :) I'll try the merge

**Comment by niess** [comment]
It worked out. Great :) Thank you again for patching this :)

**Pull request merged**
