### PR TITLE
added ssh-mitm application

### PR DESCRIPTION
**Pull request by manfred-kaiser**
I have updated the python versions in the readme and fixed the download link.

Also a project template for [ssh-mitm](https://github.com/ssh-mitm/ssh-mitm/) was added as an additional example how to deploy a python application.

### CODE REVIEW

**Comment by manfred-kaiser** [comment]
I have also added Python 3.6 to the application tests. The reason is, that python 3.5 and python 2.7 are end of life.

Python 3.6 is required by ssh-mitm, because the min. required python version is 3.6.

**Comment by manfred-kaiser** [comment]
Successful Test run: https://github.com/manfred-kaiser/python-appimage/actions/runs/918522791

**Comment by niess** [comment]
Looks great :) Thank you. It has been merged.

**Comment by manfred-kaiser** [comment]
Thanks for merging :-)

**Pull request merged**
